---
- name: install cockpit
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - cockpit
    - cockpit-bridge
    - cockpit-networkmanager
    - cockpit-packagekit
    - cockpit-selinux
    - cockpit-storaged
    - cockpit-system
    - cockpit-ws

- name: enable cockpit web console
  service:
    name: cockpit.socket
    state: started
    enabled: yes