---
- name: create users group
  group:
    name: "{{ MYUSER }}"
    gid: 2000
    state: present

- name: creating user
  user:
    append: yes
    name: "{{ MYUSER }}"
    password: "{{ MYUSER_PASS }}"
    comment: Eric The IT Guy
    group: "{{ MYUSER }}"
    home: "/home/{{ MYUSER }}"
    shell: /bin/bash
    state: present
    uid: 2000

- name: add user to sudoers
  copy:
    dest: "/etc/sudoers.d/{{ MYUSER }}"
    content: "{{ MYUSER }}     ALL=(ALL)     NOPASSWD: ALL"

- name: add key to authorized_keys
  authorized_key:
    user: "{{ MYUSER }}"
    state: present
    key: "{{ MYUSER_SSHKEY }}"