---
- name: install vim
  package:
    name: vim
    state: latest

- name: deploy vimrc
  copy:
    src: dotVimrc
    dest: "/home/{{ MYUSER }}/.vimrc"
    owner: "{{ MYUSER }}"
    group: "{{ MYUSER }}"
    mode: '0664'

- name: install vim vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "/home/{{ MYUSER }}/.vim/bundle/Vundle.vim"
    force: yes

- name: set vim permissions
  file:
    path: "/home/{{ MYUSER }}/.vim"
    owner: "{{ MYUSER }}"
    group: "{{ MYUSER }}"
    mode: '0755'
    recurse: yes

#- name: install vim plugins
#  TODO: Only run when plugins added
#  shell: vim +PluginInstall +qall