---
- name: install virtual utilities
  package:
    name: "{{ item }}"
    state: latest
# TODO: Move list to vars file
  with_items:
    - cockpit-composer
    - cockpit-machines
    - libguestfs-tools
    - libvirt-daemon-config-network
    - openssh-askpass
    #- python-libguestfs
    - qemu-kvm
    - virt-install
    - virt-manager
    - virt-top
    - virt-viewer

- name: enable libvirt service
  service:
    name: libvirtd
    state: started
    enabled: yes

- name: install container utilities
  package: 
    name: "{{ item }}"
    state: latest
# TODO: Move list to vars file
  with_items:
    - buildah
    - cockpit-podman
    - podman
    - skopeo
