FROM 10.10.10.162:5000/fedora-server:latest

COPY <<'EOF' /usr/lib/bootc/kargs.d/20-hostname.toml
kargs = ["systemd.hostname=itg-prd-arr"]
EOF

# --- WORKLOAD --- #

COPY quadlet/ /usr/share/containers/systemd/
COPY systemd/ /usr/lib/systemd/system/
RUN systemctl enable var-lib-forge.mount

# --- CLEANUP --- #
RUN bootc container lint
