# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|

  ##### DEFINE VM for oob-mgmt-server #####
  config.vm.define "itg-gitlab-01" do |config|
  config.vm.hostname = "itg-gitlab-01"
  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.22.9"
  config.vm.provider :libvirt do |v|
    v.memory = 8192
    v.cpus = 4
    end
  end
end
