# roles/do/tasks/main.yml
---
- name: Provision DigitalOcean Kubernetes cluster
  community.digitalocean.digital_ocean_kubernetes:
    name: "{{ cluster_name }}"  # This should come from vars/do.yml
    region: "{{ region }}"      # This should come from vars/do.yml
    version: "latest"
    node_pools:
      - name: "default-pool"    # Specify a name for the node pool
        size: "{{ node_size }}"  # This should come from vars/do.yml
        count: "{{ num_nodes }}" # This should come from vars/do.yml
    oauth_token: "{{ do_token }}" # This should come from vars/do.yml
  register: do_k8s_cluster

- name: Configure kubectl to use the cluster
  command: >
    doctl kubernetes cluster kubeconfig save "{{ cluster_name }}"
  environment:
    DO_API_TOKEN: "{{ do_token }}"
