# roles/do/tasks/main.yml
---
- name: Get the latest Kubernetes versions
  command: doctl kubernetes options versions --output json
  register: k8s_versions_output

- name: Parse the latest Kubernetes version
  set_fact:
    kubernetes_version: "{{ k8s_versions_output.stdout | from_json | map(attribute='slug') | last }}"

- name: Provision DigitalOcean Kubernetes cluster
  community.digitalocean.digital_ocean_kubernetes:
    oauth_token: "{{ do_token }}"
    name: "{{ cluster_name }}"
    region: "{{ region }}"
    version: "{{ kubernetes_version }}"
    auto_upgrade: yes
    node_pools:
      - name: default-pool
        size: "{{ node_size }}"
        count: "{{ num_nodes }}"
  register: do_k8s_info

- name: Configure kubectl to use the cluster
  command: doctl kubernetes cluster kubeconfig save {{ cluster_name }}
  environment:
    DO_TOKEN: "{{ do_token }}"
  when: do_k8s_info.changed
