# roles/do/tasks/teardown.yml
---
- name: Get current Kubernetes cluster information
  community.digitalocean.digital_ocean_kubernetes_info:
    name: "{{ cluster_name }}"
    oauth_token: "{{ do_token }}"
  register: do_k8s_info

- name: Fail if the Kubernetes cluster does not exist
  fail:
    msg: "The Kubernetes cluster {{ cluster_name }} does not exist or cannot be found."
  when: do_k8s_info.data is undefined

- name: Delete DigitalOcean Kubernetes cluster
  community.digitalocean.digital_ocean_kubernetes:
    name: "{{ cluster_name }}"
    region: "{{ region }}"
    oauth_token: "{{ do_token }}"
    state: absent
  when: do_k8s_info.data is defined
  register: do_k8s_delete

- name: Get current kubectl contexts
  command: kubectl config get-contexts -o name
  register: kubectl_contexts

- name: Find the correct context for the cluster
  set_fact:
    kube_context: "{{ kubectl_contexts.stdout_lines | select('search', cluster_name) | list | first }}"
  when: kubectl_contexts.stdout_lines | select('search', cluster_name) | list | length > 0

- name: Remove kubectl configuration for the cluster (ignore errors)
  command: kubectl config delete-context {{ kube_context }}
  ignore_errors: yes
  when: kube_context is defined
