FROM quay.io/fedora/fedora-bootc:latest
LABEL maintainer="eric@itguyeric.com"

# --- USERS --- #

RUN --mount=type=secret,id=rootpw \
    echo "root:$(cat /run/secrets/rootpw)" | chpasswd -e

COPY <<'EOF' /usr/lib/sysusers.d/itg-users.conf
#Type Name      ID         GECOS                 Home             Shell
g     ansible	1000
u     ansible   1000:1000  "Ansible SVC"	/home/ansible    /bin/bash
g     itguyeric 1001
u     itguyeric 1001:1001  "Eric the IT Guy"	/home/itguyeric  /bin/bash
g     worker    2000
u     worker    2000:2000  "Container SVC"	/home/worker     /bin/bash
m     ansible   wheel
m     itguyeric wheel
EOF
RUN systemd-sysusers

RUN echo '%wheel ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/wheel-nopasswd && \
    chmod 440 /etc/sudoers.d/wheel-nopasswd

RUN printf 'PasswordAuthentication no\nPermitRootLogin no\n' \
    > /etc/ssh/sshd_config.d/20-hardening.conf

# --- SSH KEYS --- #

COPY ansible/roles/common/files/id_rsa_ans.pub /usr/share/ssh-keys/ansible.pub
COPY ansible/roles/common/files/id_rsa_itg.pub /usr/share/ssh-keys/itguyeric.pub

COPY <<'EOF' /usr/lib/tmpfiles.d/ssh-authorized-keys.conf
d /home/ansible                          0700 ansible   ansible   -
d /home/ansible/.ssh                     0700 ansible   ansible   -
C /home/ansible/.ssh/authorized_keys     0600 ansible   ansible   - /usr/share/ssh-keys/ansible.pub
d /home/itguyeric                        0700 itguyeric itguyeric -
d /home/itguyeric/.ssh                   0700 itguyeric itguyeric -
C /home/itguyeric/.ssh/authorized_keys   0600 itguyeric itguyeric - /usr/share/ssh-keys/itguyeric.pub
EOF

# --- SYSTEM --- #

RUN dnf install -y cockpit-networkmanager cockpit-podman cockpit-storaged cockpit-system podman qemu-guest-agent tuned vim-enhanced && \
    dnf remove -y iscsi-initiator-utils kdump-utils kexec-tools && \
    dnf clean all && \
    rm -rf /var/cache/* /var/lib/dnf /var/log/* /run/dnf /run/tuned

COPY <<'EOF' /usr/lib/tmpfiles.d/tuned.conf
d /var/lib/tuned 0755 root root - -
EOF

RUN echo 'virtual-guest' > /etc/tuned/active_profile && \
    echo 'manual' > /etc/tuned/profile_mode

COPY <<'EOF' /usr/lib/bootc/kargs.d/10-console.toml
kargs = ["loglevel=3"]
EOF

RUN systemctl enable podman.socket sshd systemd-journald-audit.socket tuned

# --- CLEANUP --- #

RUN bootc container lint
