FROM quay.io/fedora/fedora-bootc:latest
LABEL maintainer="eric@itguyeric.com"

# --- USERS --- #

RUN groupadd -g 1000 ansible && useradd -u 1000 -g 1000 -G wheel -m -s /bin/bash ansible && \
    groupadd -g 1001 itguyeric && useradd -u 1001 -g 1001 -G wheel -m -s /bin/bash itguyeric && \
    groupadd -g 2000 worker && useradd -u 2000 -g 2000 -m -s /bin/bash worker

RUN echo '%wheel ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/wheel-nopasswd && \
    chmod 440 /etc/sudoers.d/wheel-nopasswd

RUN printf 'PasswordAuthentication no\nPermitRootLogin no\n' \
    > /etc/ssh/sshd_config.d/20-hardening.conf

# --- PACKAGES --- #

RUN dnf install -y cockpit-networkmanager cockpit-podman cockpit-storage cockpit-system podman qemu-guest-agent tuned vim-enhanced && \
    dnf remove -y kdump-utils kexec-tools && \
    dnf clean all
RUN systemctl enable cockpit.socket podman.socket sshd

# --- SSH KEYS (bootc-idiomatic) --- #

COPY ansible/roles/common/files/id_rsa_ans.pub /usr/share/ssh-keys/ansible.pub
COPY ansible/roles/common/files/id_rsa_itg.pub /usr/share/ssh-keys/itguyeric.pub

COPY <<'EOF' /usr/lib/tmpfiles.d/ssh-authorized-keys.conf
d /home/ansible                          0700 ansible   ansible   -
d /home/ansible/.ssh                     0700 ansible   ansible   -
C /home/ansible/.ssh/authorized_keys     0600 ansible   ansible   - /usr/share/ssh-keys/ansible.pub
d /home/itguyeric                        0700 itguyeric itguyeric -
d /home/itguyeric/.ssh                   0700 itguyeric itguyeric -
C /home/itguyeric/.ssh/authorized_keys   0600 itguyeric itguyeric - /usr/share/ssh-keys/itguyeric.pub
EOF

# --- CLEANUP --- #

RUN echo 'itg-dev-bootc' > /etc/hostname

RUN rm /var/{cache,lib}/dnf /var/lib/rhsm /var/cache/ldconfig -rf
RUN bootc container lint
