## general
set-option -g allow-rename off 			# disable window rename
set -g history-limit 5000			# increase history limit

set -g renumber-windows on			# renumber windows when a window is closed

## display
set -g default-terminal "screen-256color" 	# colors!
setw -g xterm-keys on

## navigation

bind h split-window -h				# rebind window keys
bind v split-window -v
unbind '"'
unbind %

bind -n M-Left select-pane -L			# switch panes using Alt-arrow
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D


