---
- hosts: all
  become: true
  vars:
    timesync_ntp_servers:
      - hostname: time-b-g.nist.gov
        iburst: yes
      - hostname: time-b-wwv.nist.gov
        iburst: yes
      - hostname: time-d-b.nist.gov
        iburst: yes
  roles:
    - role: tasks/rhel-system-roles.timesync
