## general
set-option -g allow-rename off 			# disable window rename
set -g history-limit 5000			# increase history limit

set -g renumber-windows on			# renumber windows when a window is closed

## display
set -g default-terminal "screen-256color" 	# colors!
set -g set-titles off			        # set terminal title
setw -g xterm-keys on

## navigation

bind h split-window -h				# rebind window keys
bind v split-window -v
unbind '"'
unbind %
