FROM 10.10.10.162:5000/fedora-server:latest

COPY <<'EOF' /usr/lib/bootc/kargs.d/20-hostname.toml
kargs = ["systemd.hostname=itg-dev-bootc"]
EOF

# --- WORKLOAD --- #

# --- CLEANUP --- #
RUN bootc container lint
