# roles/civo/tasks/main.yml
---
- name: Provision Civo Kubernetes cluster
  community.general.civo_kubernetes_cluster:
    state: present
    name: "{{ cluster_name }}"
    num_nodes: "{{ num_nodes }}"
    size: "{{ node_size }}"
    region: "{{ region }}"
    api_key: "{{ civo_token }}"
  register: civo_k8s_cluster

- name: Configure kubectl to use the cluster
  command: >
    civo kubernetes config "{{ cluster_name }}" --save
  environment:
    CIVO_API_KEY: "{{ civo_token }}"
