---
- name: Delete Civo Kubernetes cluster
  command: >
    civo kubernetes remove {{ cluster_name }}
    --region {{ region }}
    --yes
  environment:
    CIVO_API_KEY: "{{ civo_token }}"
  register: civo_k8s_remove
  failed_when: civo_k8s_remove.rc != 0
  changed_when: "'has been deleted' in (civo_k8s_remove.stdout | regex_replace('\\x1b\\[[0-9;]*m', ''))"

- name: Wait for the cluster deletion to complete
  pause:
    minutes: 2

- name: Remove kubectl context for the cluster (ignore errors)
  command: >
    kubectl config delete-context {{ cluster_name }}
  ignore_errors: yes

- name: Remove kubectl cluster for the cluster (ignore errors)
  command: >
    kubectl config delete-cluster {{ cluster_name }}
  ignore_errors: yes

- name: Remove kubectl user for the cluster (ignore errors)
  command: >
    kubectl config unset users.{{ cluster_name }}
  ignore_errors: yes

