- hosts: gcp
  vars_files:
    - ../vars/gcp.yml

  tasks:
    - name: Delete Kubernetes cluster on GCP
      command: >
        gcloud container clusters delete {{ cluster_name }} --zone {{ zone }} --project {{ gcp_project }} --quiet
      ignore_errors: yes

    - name: Remove context from kubeconfig
      command: kubectl config delete-context {{ cluster_name }}
      ignore_errors: yes

    - name: Remove cluster from kubeconfig
      command: kubectl config delete-cluster {{ cluster_name }}
      ignore_errors: yes

    - name: Remove user from kubeconfig
      command: kubectl config unset users.{{ cluster_name }}
      ignore_errors: yes

