---
- hosts: servers
  become: yes
  gather_facts: no
  tasks:
#    - name: install basic utilities
#      import_tasks: tasks/utilities.yml

#    - name: deploy bashrc
#  import_tasks: tasks/bashrc.yml
