# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.2.0
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/ddb-app: registry
    io.kubernetes.cri-o.ContainerType/ddb-app: container
    io.kubernetes.cri-o.SandboxID/ddb-app: 767ac9f4f865b7d1208724134d28fbdaf9cc6474a20397a26505e03ffd15b51
    io.kubernetes.cri-o.TTY/ddb-app: "true"
    io.podman.annotations.autoremove/ddb-app: "FALSE"
    io.podman.annotations.init/ddb-app: "FALSE"
    io.podman.annotations.privileged/ddb-app: "FALSE"
    io.podman.annotations.publish-all/ddb-app: "FALSE"
  creationTimestamp: "2023-03-07T17:55:21Z"
  labels:
    app: ddb-proxy
  name: ddb-proxy
spec:
  restartPolicy: Never 
  containers:
  - args:
    - node
    - index.js
    env:
    - name: VIRTUAL_HOST
      value: ddb-proxy.itguyeric.com
    - name: VIRTUAL_PORT
      value: "3000"
    - name: LETSENCRYPT_HOST
      value: ddb-proxy.itguyeric.com
    image: ghcr.io/mrprimate/ddb-proxy:latest
    name: ddb-app
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    stdin: true
    tty: true
  hostname: ddb-proxy
  
status: {}
