apiVersion: v1
kind: Pod
metadata:
  name: nginx-proxy-manager
spec:
  containers:
    - name: npm
      image: docker.io/jc21/nginx-proxy-manager:latest
      ports:
        - containerPort: 81
          hostPort: 81
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        - containerPort: 3000
          hostPort: 3000
      env:
        - name: TZ
          value: America/Chicago
        - name: DB_SQLITE_FILE
          value: /data/database.sqlite
        - name: NODE_ENV
          value: production
        - name: NODE_OPTIONS
          value: --openssl-legacy-provider
      volumeMounts:
        - mountPath: /data
          name: npm-data
        - mountPath: /etc/letsencrypt
          name: npm-ssl
        - mountPath: /var/log
          name: npm-logs
  volumes:
    - name: npm-data
      hostPath:
        path: /var/lib/containers/nginx-proxy-manager/data
        type: Directory
    - name: npm-ssl
      hostPath:
        path: /var/lib/containers/nginx-proxy-manager/letsencrypt
        type: Directory
    - name: npm-logs
      hostPath:
        path: /var/lib/containers/nginx-proxy-manager/logs
        type: Directory

