# 
---

- hosts: localhost
  connection: local
  gather_facts: false

  vars:
  - DO_API_TOKEN: 740be747ad0307d17ac33d268032425cb41beb3426d09b47d627c9baeba1e4e3

  tasks:
  - name: update system
    yum:
      name: "*"
      state: latest
