# Docs: https://docs.ansible.com/ansible/latest/modules/user_module.html

---

- name: Create the "ehendricks" account
  user:
    name: ehendricks
    comment: Eric Hendricks
    uid: 2000
    group: ehendricks
    groups: wheel
    home: /home/ehendricks
    shell: /bin/bash
    ssh_key_file: /home/ehendricks/.ssh/id_rsa_do
    state: present
