FROM 10.10.10.162:5000/fedora-server:latest

COPY <<'EOF' /usr/lib/bootc/kargs.d/20-hostname.toml
kargs = ["systemd.hostname=itg-prd-forge"]
EOF

COPY <<'EOF' /usr/lib/NetworkManager/conf.d/20-keep-hostname.conf
[main]
hostname-mode=none

[connection]
ipv4.dhcp-hostname=itg-prd-forge
EOF

# --- WORKLOAD --- #

COPY systemd/ /usr/lib/systemd/system/
COPY quadlet/ /usr/share/containers/systemd/
RUN systemctl enable forge-data-init.service var-lib-forge.mount

COPY <<'EOF' /usr/lib/tmpfiles.d/forge-data-dirs.conf
d /var/lib/forge/pgdata   0700 999  999  -
d /var/lib/forge/forgejo  0700 1001 1001 -
EOF

# --- CLEANUP --- #

