# roles/gcp/tasks/main.yml
---
- name: Provision GKE cluster
  google.cloud.gcp_container_cluster:
    name: "{{ cluster_name }}"
    location: "{{ zone }}"
    initial_node_count: "{{ num_nodes }}"
    project: "{{ gcp_project }}"
    auth_kind: application
    node_config:
      machine_type: "{{ node_size }}"
      disk_size_gb: "{{ disk_size }}"

- name: Retrieve GKE cluster information
  google.cloud.gcp_container_cluster_info:
    location: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: application
  register: gke_cluster_info

- name: Configure kubectl to use the cluster
  command: >
    gcloud container clusters get-credentials {{ cluster_name }} --zone {{ zone }} --project {{ gcp_project }}
