# roles/gcp/tasks/main.yml
---
- name: Provision GKE cluster
  google.cloud.gcp_container_cluster:
    name: "{{ cluster_name }}"
    location: "{{ zone }}"
    initial_node_count: "{{ num_nodes }}"
    project: "{{ gcp_project }}"
    auth_kind: application
    node_config:
      machine_type: "{{ node_size }}"
      disk_size_gb: "{{ disk_size }}"

- name: Configure kubectl to use the cluster
  gcp_container_cluster_info:
    cluster_name: "{{ cluster_name }}"
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    credentials_file: "{{ gcp_service_account_file }}"
  register: gke_kubeconfig

- name: Save kubeconfig for GKE
  local_action:
    module: lineinfile
    path: "~/.kube/config"
    line: "{{ gke_kubeconfig.stdout }}"
