# roles/gcp/tasks/update.yml
---
- name: Get the latest GKE master version
  google.cloud.gcp_container_cluster_info:
    name: "{{ cluster_name }}"
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    credentials_file: "{{ gcp_service_account_file }}"
  register: gcp_cluster_info

- name: Update GKE cluster to the latest available version
  google.cloud.gcp_container_cluster:
    name: "{{ cluster_name }}"
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    credentials_file: "{{ gcp_service_account_file }}"
    node_version: "{{ gcp_cluster_info.instance.latestMasterVersion }}"
    master_version: "{{ gcp_cluster_info.instance.latestMasterVersion }}"
    update: true
  when: gcp_cluster_info.instance.currentMasterVersion != gcp_cluster_info.instance.latestMasterVersion
