- hosts: localhost
  vars_files:
    - ../vars/gcp.yml

  tasks:
    - name: Check if the Kubernetes cluster exists
      command: gcloud container clusters describe {{ cluster_name }} --zone {{ zone }}
      register: cluster_exists
      ignore_errors: true

    - name: Delete Kubernetes cluster on GCP
      command: gcloud container clusters delete {{ cluster_name }} --zone {{ zone }} --quiet
      when: cluster_exists is succeeded

    - name: Remove context from kubeconfig
      command: kubectl config delete-context {{ cluster_name }}
      ignore_errors: yes
      when: cluster_exists is succeeded

    - name: Remove cluster from kubeconfig
      command: kubectl config delete-cluster {{ cluster_name }}
      ignore_errors: yes
      when: cluster_exists is succeeded

    - name: Remove user from kubeconfig
      command: kubectl config unset users.{{ cluster_name }}
      ignore_errors: yes
      when: cluster_exists is succeeded
