- hosts: gcp
  vars_files:
    - ../vars/gcp.yml
  collections:
    - google.cloud

  tasks:
    - name: Check if the Kubernetes cluster exists
      google.cloud.gcp_container_cluster_info:
        name: "{{ cluster_name }}"
        location: "{{ zone }}"
        project: "{{ gcp_project }}"
      register: cluster_info
      ignore_errors: yes

    - name: Create Kubernetes cluster on GCP
      google.cloud.gcp_container_cluster:
        name: "{{ cluster_name }}"
        location: "{{ zone }}"
        project: "{{ gcp_project }}"
        node_pools:
          - name: default-pool
            initial_node_count: "{{ num_nodes }}"
            config:
              disk_size_gb: "{{ disk_size }}"
        state: present
      when: cluster_info is failed

    - name: Wait for Kubernetes cluster to be fully operational
      command: >
        gcloud container clusters describe {{ cluster_name }} --zone {{ zone }} --project {{ gcp_project }} --format="value(status)"
      register: cluster_status
      retries: 30
      delay: 30
      until: cluster_status.stdout == "RUNNING"

    - name: Debug cluster creation result
      debug:
        msg: "Cluster creation result: {{ cluster_info }}"

    - name: Include the upgrade tasks
      import_tasks: ../roles/gcp/tasks/upgrade-k8s.yml
      when: cluster_info is succeeded

    - name: Call deploy_itg tasks
      import_tasks: ../roles/gcp/tasks/deploy_itg.yml
      when: cluster_info is succeeded

